CREATE TABLE events (
                        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL,
                        description TEXT,
                        created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP(6)
);


CREATE TABLE topics (
                        topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL,
                        created_by UUID NOT NULL,
                        event_id BIGINT,
                        created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_topics_users
                            FOREIGN KEY (created_by) REFERENCES users(id)
                                ON DELETE CASCADE,
                        CONSTRAINT fk_topics_events
                            FOREIGN KEY (event_id) REFERENCES events(event_id)
                                ON DELETE CASCADE
);


CREATE TABLE user_profiles (
                               profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id UUID NOT NULL UNIQUE,
                               display_name VARCHAR(100),
                               avatar_url TEXT,
                               bio TEXT,
                               created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_user_profiles_users
                                   FOREIGN KEY (user_id) REFERENCES users(id)
                                       ON DELETE CASCADE
);


CREATE TABLE posts (
                       post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       author_id UUID NOT NULL,
                       topic_id BIGINT,
                       content TEXT NOT NULL,
                       created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP(6),
                       CONSTRAINT fk_posts_users
                           FOREIGN KEY (author_id) REFERENCES users(id)
                               ON DELETE CASCADE,
                       CONSTRAINT fk_posts_topics
                           FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
                               ON DELETE CASCADE
);

CREATE TABLE comments (
                          comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          post_id BIGINT NOT NULL,
                          author_id UUID NOT NULL,
                          content TEXT NOT NULL,
                          created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_comments_posts
                              FOREIGN KEY (post_id) REFERENCES posts(post_id)
                                  ON DELETE CASCADE,
                          CONSTRAINT fk_comments_users
                              FOREIGN KEY (author_id) REFERENCES users(id)
                                  ON DELETE CASCADE
);
